# Generated by Django 3.1.4 on 2020-12-22 08:22

from django.db import migrations
from django.core.management import call_command

def forwards_func(apps, schema_editor):
    product = apps.get_model('payments', 'Product')
    product.objects.create(
        product_id = 1,
        title = 'HD DSLR Image- Himalaya',
        description = 'Must Buy!',
        price = 0.02,
        product_image = "actual/actual.jpg",
        product_thumb = "thumb/thumb.jpg"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
