# Generated by Django 3.1.4 on 2020-12-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_amount',
            field=models.FloatField(default=0),
        ),
    ]
